name: ğŸŒ Frontend Applications CI

on:
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./crates/banyan-core-service/frontend

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Set up Node.js with Yarn
        uses: actions/setup-node@v2
        with:
          node-version-file: ./crates/banyan-core-service/frontend/.nvmrc
          cache-dependency-path: ./crates/banyan-core-service/frontend/yarn.lock
          cache: 'yarn'

      - name: Install Dependencies
        run: yarn install

      - name: Build Core Web Application
        run: yarn build
