name: ğŸŒ Continuous Integration
on:
  pull_request:
    branches:
      - main
  push:
    tags:
    branches:
      - main

jobs:
  build_core_frontend:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./crates/banyan-core-service/frontend

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Node.js with NPM
        uses: actions/setup-node@v2
        with:
          node-version-file: ./crates/banyan-core-service/frontend/.nvmrc
          cache-dependency-path: ./crates/banyan-core-service/frontend/package-lock.json
          cache: 'npm'
      
      - name: Install Dependencies
        run: npm ci
      
      - name: Build Core Web Application
        run: npm run build

